### ISSUE TITLE
Please provide a more informative README

### ISSUE THREAD

**Issue by pcav** [jeroenvanderzwam/buienradar#1]
Instead of the one created by Plugin Builder.
Thanks.

**Comment by jeroenvanderzwam** [comment]
I've updated the readme. So people can more easily install the plugin. And a small explanation of what the plugin is

**Comment by bijwaard** [comment]
Hi Jeroen,
I got curious after installing your plugin. Took a minute to find the configuration under "Web/Buienradar Plugin", you could that to the readme as well;-)
Thanks for this plugin!
Dennis
