### ISSUE TITLE
Kon plug-in 'buienradar_plugin' niet laden wegens een fout bij het aanroepen van de methode classFactory() 

### ISSUE THREAD

**Issue by NvBgm** [jeroenvanderzwam/buienradar#2]
Kon plug-in 'buienradar_plugin' niet laden wegens een fout bij het aanroepen van de methode classFactory() 

ModuleNotFoundError: No module named 'pandas' 
Traceback (most recent call last):
  File "C:/OSGEO4~1/apps/qgis/./python\qgis\utils.py", line 334, in _startPlugin
    plugins[packageName] = package.classFactory(iface)

Python versie: 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)] 
QGIS versie: 3.10.0-A CoruÃ±a A CoruÃ±a, 6c816b4204

**Comment by jeroenvanderzwam** [comment]
als het goed is heb je een osgeo shell geinstalleerd.
open deze:
type daarin:
- py3_env (dit zet de juiste variabelen voor python3)
- pip3 install pandas
- pip3 install xmltodict

zou je me willen laten weten als het je is gelukt?

**Comment by NvBgm** [comment]
@Jeroen.
Volgens mij zegt onderstaande voldoende.
![image](https://user-images.githubusercontent.com/8125819/69813948-8a1b6e00-11f3-11ea-810c-10a305c3dbda.png)

Lag inderdaad aan de variabelen python3
Zoals jij aangaf uitgevoerd en daarna nog eens de plugin herinstalleert.

Bedank...
